worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    # Базові налаштування оптиміза
    sendfile        on;
    keepalive_timeout  65;

    # Блок налаштування нашого сервера
    server {
        listen 80;
        server_name localhost;

        # Базові заголовки безпеки (захист від XSS та Clickjacking)
        add_header X-Frame-Options "SAMEORIGIN";
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Content-Type-Options "nosniff";

        location / {
            # Перенаправляємо весь трафік на наш Node.js контейнер
            proxy_pass http://web:3000;
            proxy_http_version 1.1;
            
            # [ВИПРАВЛЕНО] H2C Smuggling: 
            # Видалено небезпечні заголовки Upgrade та Connection, 
            # оскільки застосунок не вимагає WebSockets.
            
            # [ВИПРАВЛЕНО] Host Header Injection:
            # Використовуємо безпечну змінну $proxy_host замість $host
            proxy_set_header Host $proxy_host;
            
            # Передаємо реальну IP користувача до Node.js
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
