global:
  scrape_interval: 15s # Як часто Prometheus буде збирати дані (кожні 15 секунд)
  evaluation_interval: 15s

scrape_configs:
  # 1. Prometheus збирає метрики сам із себе
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # 2. Prometheus збирає метрики з нашого котячого блогу (Node.js)
  - job_name: "cat_blog_node"
    static_configs:
      - targets: ["web:3000"]
