global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cat_blog_nodejs'
    static_configs:
      - targets: ['web:80']

  - job_name: 'prometheus_self'
    static_configs:
      - targets: ['localhost:9090']
